/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_pos_system;

import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author GalleComZone
 */
public class AddItem extends javax.swing.JFrame {
  DBConnection db = new DBConnection();

    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents(); 
        loadBGImage();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Z = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        logo6 = new javax.swing.JLabel();
        pno = new javax.swing.JTextField();
        bgg7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add item");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1Z.setBackground(new java.awt.Color(3, 25, 87));
        jTable1Z.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1Z.setForeground(new java.awt.Color(255, 255, 255));
        jTable1Z.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prod: No", "Name", "Avail:QTY", "U-Price(INR)"
            }
        ));
        jScrollPane1.setViewportView(jTable1Z);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 40, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 160, 30));

        qty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QTY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        UP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Unit price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        Clear.setBackground(new java.awt.Color(8, 8, 126));
        Clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearMouseExited(evt);
            }
        });
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 100, 30));

        Add.setBackground(new java.awt.Color(8, 8, 126));
        Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("ADD");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 100, 30));
        getContentPane().add(logo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 100));

        pno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(pno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 160, 30));
        getContentPane().add(bgg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Display();
    }//GEN-LAST:event_formWindowOpened

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       try {
            String msg = "INSERT INTO item (pno,name,qty,unit_price) values(?,?,?,?)";
          pst = db.con.prepareStatement(msg);
          
            pst.setString(1, pno.getText());
            pst.setString(2, name.getText());
            pst.setString(3, qty.getText());
            pst.setString(4, UP.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "OK,New Product Added Sucssussfuly");
            

         
            clear();
            
        } catch (SQLException ex) {
            Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       pno.setText("");
        name.setText("");
         qty.setText("");
          UP.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        Add.setBackground(new Color(9,56,248)); 
        Add.setForeground(new Color(255,204,0));
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        Add.setBackground(new Color(8,8,126));
      Add.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_AddMouseExited

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearMouseClicked

    private void ClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseEntered
        Clear.setBackground(new Color(9,56,248)); 
        Clear.setForeground(new Color(255,204,0));
    }//GEN-LAST:event_ClearMouseEntered

    private void ClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseExited
       Clear.setBackground(new Color(8,8,126));
      Clear.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ClearMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField UP;
    private javax.swing.JLabel bgg7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Z;
    private javax.swing.JLabel logo6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pno;
    private javax.swing.JTextField qty;
    // End of variables declaration//GEN-END:variables
 private void loadBGImage() {
        bgg7.setIcon(resize1("src\\bgg2.png"));
          logo6.setIcon(resize2("src\\ba6.jpeg"));
       
    }

    private Icon resize1(String image) {
        ImageIcon icon = new ImageIcon(image);
        Image scaled = icon.getImage().getScaledInstance(bgg7.getWidth(), bgg7.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);

    }
    private Icon resize2(String image) {
        ImageIcon icon = new ImageIcon(image);
        Image scaled = icon.getImage().getScaledInstance(logo6.getWidth(), logo6.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);

    }

   
    private void Display() {

        try {
            String msg = "SELECT * FROM item";
            pst = db.con.prepareStatement(msg);
            rs = pst.executeQuery();
            while (rs.next()) {
                String pno = rs.getString(1);
                String name = rs.getString(2);
                String qty = rs.getString(3);
                String unit_price = rs.getString(4);

                DefaultTableModel tablemodel = (DefaultTableModel) jTable1Z.getModel();

                Object[] data = new Object[4];
                data[0] = pno;
                data[1] = name;
                data[2] = qty;
                data[3] = unit_price;

                tablemodel.addRow(data);

            }
        } catch (SQLException ex) {;

            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    private void clear() {
 pno.setText("");  
 name.setText("");  
 qty.setText("");
 UP.setText("");  
    }
}
