/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_pos_system;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author GalleComZone
 */
public class billZoom extends javax.swing.JFrame {
 private String billContent;
    /**
     * Creates new form billZoom
     */
    public billZoom(String billDetails) {
        initComponents();
        this.billContent = billDetails; 
        loadBGImage(); 
        setLocationRelativeTo(null);
        Display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtZarea = new javax.swing.JTextArea();
        bgg3 = new javax.swing.JLabel();
        bgg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtZarea.setColumns(20);
        txtZarea.setRows(5);
        jScrollPane1.setViewportView(txtZarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 480));
        getContentPane().add(bgg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 80));
        getContentPane().add(bgg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billZoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billZoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billZoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billZoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new billZoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgg2;
    private javax.swing.JLabel bgg3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtZarea;
    // End of variables declaration//GEN-END:variables

    
    private void loadBGImage() {
        bgg2.setIcon(resize1("src\\wall3.png"));
          bgg3.setIcon(resize2("src\\ba6.jpeg"));
      
    }

    private Icon resize1(String image) {
        ImageIcon icon = new ImageIcon(image);
        Image scaled = icon.getImage().getScaledInstance(bgg2.getWidth(), bgg2.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);

    }
     private Icon resize2(String image) {
        ImageIcon icon = new ImageIcon(image);
        Image scaled = icon.getImage().getScaledInstance(bgg3.getWidth(), bgg3.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);

    }

     private void Display() {
        String body = billContent;
        txtZarea.setText(body);
        txtZarea.setEditable(false);
        
    }
}
