/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_pos_system;

import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.net.URLEncoder;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GalleComZone
 */
public class Send extends javax.swing.JFrame {
private String billContent;
    /**
     * Creates new form Send
     */
    public Send(String billText) {
        initComponents();
        this.billContent = billText; 
        setLocationRelativeTo(null);
         loadBGImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BgSend = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Send ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 340, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whats1.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 60, 60));

        btnM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });
        getContentPane().add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 60, 60));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 204, 0));
        jLabel1.setText("Enter Your  W:Phone Number Or E-mail...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 340, 30));
        getContentPane().add(BgSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
           String msg = billContent;
//            String msg = txtArea.getText();
            String subject = "Test whatsapp Massage";
            String number = "+94" + txt1.getText();

            String endingMsg = URLEncoder.encode(msg, "UTF-8");
            String url = "https://wa.me/" + number + "?text=" + endingMsg;
            Desktop.getDesktop().browse(URI.create(url));

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
     
        
         String sentTo = txt1.getText();
        String subject = "Test Mail for Desktop app";
        String message = billContent;
        sendEmail(sentTo, subject, message);
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Send.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Send().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgSend;
    private javax.swing.JButton btnM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables

     private void loadBGImage() {
        BgSend.setIcon(resize1("src\\bgg2.png"));
         btnM.setIcon(resize2("src\\email5.png"));
       
    }

    private Icon resize1(String image) {
        ImageIcon icon = new ImageIcon(image);
        Image scaled = icon.getImage().getScaledInstance(BgSend.getWidth(), BgSend.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);

    }

    private Icon resize2(String image) {
 ImageIcon icon = new ImageIcon(image);
        Image scaled = icon.getImage().getScaledInstance(btnM.getWidth(), btnM.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);    }

    private void sendEmail(String sentTo, String subject, String messageText) {




        final String fromEmail = "contact.kawya@gmail.com"; // Your Gmail
        final String password = "fcfi doiv lrtg xvjq";     // App password from Gmail (not your actual password)

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true"); // TLS

        javax.mail.Session session = javax.mail.Session.getInstance(props, new javax.mail.Authenticator() {
           
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication(fromEmail, password);
            }
        });

        try {
            javax.mail.Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromEmail));
            message.setRecipients(
                    javax.mail.Message.RecipientType.TO, InternetAddress.parse(sentTo)
            );
            message.setSubject(subject);
            message.setText(messageText);

            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Email sent successfully!");

        } catch (MessagingException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Email failed: " + e.getMessage());
        }



















    }
}
